# PostgreSQL with PostGIS. PostgreSQL 14+ and PostGIS 3.0+ are required.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
#
# Configure Using Gemfile:
#   gem "pg"
#   gem "activerecord-postgis-adapter"
#
default: &default
  adapter: postgis
  encoding: unicode
  # PostGIS schema configuration
  schema_search_path: public
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: shiojiri_rainbow_seeker_development
    # Docker Compose environment variables (optional for local development)
    # When DATABASE_HOST is set, use Docker Compose configuration
    <% if ENV["DATABASE_HOST"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
    username: <%= ENV.fetch("POSTGRES_USER") { "shiojiri" } %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    <% end %>
    # The specified database role being used to connect to PostgreSQL.
    # To create additional roles in PostgreSQL see `$ createuser --help`.
    # When left blank, PostgreSQL will use the default role. This is
    # the same name as the operating system user running Rails.
    #username: shiojiri_rainbow_seeker
    # The password associated with the PostgreSQL role (username).
    #password:
    # Connect on a TCP socket. Omitted by default since the client uses a
    # domain socket that doesn't need configuration. Windows does not have
    # domain sockets, so uncomment these lines.
    #host: localhost
    # The TCP port the server listens on. Defaults to 5432.
    # If your server runs on a different port number, change accordingly.
    #port: 5432
  # Solid Cache database (PostgreSQL-based cache)
  cache:
    <<: *primary_development
    database: shiojiri_rainbow_seeker_development_cache
    migrations_paths: db/cache_migrate
  # Solid Queue database (PostgreSQL-based job queue)
  queue:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: shiojiri_rainbow_seeker_development_queue
    migrations_paths: db/queue_migrate
  # Solid Cable database (PostgreSQL-based ActionCable)
  cable:
    <<: *primary_development
    database: shiojiri_rainbow_seeker_development_cable
    migrations_paths: db/cable_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary: &primary_test
    <<: *default
    database: shiojiri_rainbow_seeker_test
  # Solid Cache database for test
  cache:
    <<: *primary_test
    database: shiojiri_rainbow_seeker_test_cache
    migrations_paths: db/cache_migrate
  # Solid Queue database for test
  queue:
    <<: *primary_test
    database: shiojiri_rainbow_seeker_test_queue
    migrations_paths: db/queue_migrate
  # Solid Cable database for test
  cable:
    <<: *primary_test
    database: shiojiri_rainbow_seeker_test_cable
    migrations_paths: db/cable_migrate

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgis://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: shiojiri_rainbow_seeker_production
    username: shiojiri_rainbow_seeker
    password: <%= ENV["SHIOJIRI_RAINBOW_SEEKER_DATABASE_PASSWORD"] %>
    host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
    port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  cache:
    <<: *primary_production
    database: shiojiri_rainbow_seeker_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: shiojiri_rainbow_seeker_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: shiojiri_rainbow_seeker_production_cable
    migrations_paths: db/cable_migrate
